before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'labs.matiasbontempo.com' >> ~/.ssh/known_hosts

stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://ewgn.labs.matiasbontempo.com
  image: node:latest
  script:
    - ssh dokku@labs.matiasbontempo.com apps:create ewgn 2> /dev/null || echo "App already exists"
    - ssh dokku@labs.matiasbontempo.com config:set ewgn DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    - ssh dokku@labs.matiasbontempo.com storage:mount ewgn /var/lib/dokku/data/storage/ewgn:/usr/src/app/persist 2> /dev/null || echo "Mount path already exists"
    - git push dokku@labs.matiasbontempo.com:ewgn HEAD:refs/heads/master --force
