before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'labs.matiasbontempo.com' >> ~/.ssh/known_hosts

stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://${CI_PROJECT_NAME}.labs.matiasbontempo.com
  image: node:latest
  script:
    - ssh dokku@labs.matiasbontempo.com apps:create ${CI_PROJECT_NAME} 2> /dev/null || echo "App already exists"
    - git push dokku@labs.matiasbontempo.com:${CI_PROJECT_NAME} HEAD:refs/heads/master --force
